version: '3.4'

services:
  dvf:
    image: dvf
    build:
      context: DVF
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
  db:
    image: custom
    build:
      context: DB
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
